### ISSUE TITLE
Allow admins to track ankle monitors

### ISSUE THREAD

**Issue by sabrinagannon** [sansbrina/new_sanctuary_asylum#2]
[Original issue](https://github.com/CZagrobelny/new_sanctuary_asylum/issues/249), copied here so I can track my work done towards completing it.

### Background

When our Friends are monitored electronically with an ankle monitor, we want to track this in the same way that we track Detentions for Friends.

### Implementation steps

- [x]  Database changes: Create a AnkleMonitor table with columns for 'date_applied' (datetime), 'date_removed' (date_time), bi_smart_link (boolean), 'notes' (text), 'friend_id'

- [x] Create AnkleMonitor model

On the admin edit friend detention tab (https://github.com/CZagrobelny/new_sanctuary_asylum/blob/master/app/views/admin/friends/_detention_form_fields.html.erb), add an Ankle Monitor section below 'Detentions'. Use the 'Detentions' functionality on this page as a template to build out the following:

- [x]   an admin should be able to view the Friend's ankle monitoring history

- [x] an admin can edit an instance of ankle monitoring

- [x] an admin can add a new ankle monitoring instance for a Friend

- [x] an admin can delete a Friend's ankle monitoring instance

**Comment by sabrinagannon** [comment]
![ankle](https://user-images.githubusercontent.com/5974006/66693010-24d6e200-ec72-11e9-8aff-09d463f295a1.gif)
